[2024-10-14T02:26:47.001+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:26:47.006+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:26:47.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.038+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:26:47.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:26:47.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.077 seconds
[2024-10-14T02:27:17.473+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:27:17.476+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:17.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.491+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:17.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:27:17.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:27:48.009+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:27:48.013+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:48.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.025+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:48.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:27:48.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:28:18.711+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:28:18.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:18.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.729+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:18.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:28:18.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.042 seconds
[2024-10-14T02:28:49.243+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:28:49.247+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:49.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.271+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:49.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:28:49.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.063 seconds
[2024-10-14T02:29:20.007+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:29:20.011+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:20.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.029+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:20.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:29:20.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.062 seconds
[2024-10-14T02:29:50.607+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:29:50.611+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:50.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.622+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:50.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:29:50.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.041 seconds
[2024-10-14T02:30:20.967+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:20.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:30:20.971+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:20.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:20.987+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:20.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:30:20.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:21.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:30:51.920+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:30:51.923+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:51.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.944+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:51.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:30:51.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.064 seconds
[2024-10-14T02:31:22.992+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:22.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:31:22.997+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:22.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:23.016+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:23.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:31:23.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:23.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:31:53.459+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:31:53.467+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:53.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.494+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:53.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:31:53.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.065 seconds
[2024-10-14T02:32:23.697+0000] {processor.py:186} INFO - Started process (PID=755) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:32:23.700+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:23.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:23.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:32:23.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:32:54.453+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:32:54.459+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:54.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.476+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:54.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:32:54.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.051 seconds
[2024-10-14T02:33:25.151+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:33:25.155+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:25.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.170+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:25.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:33:25.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T02:33:55.970+0000] {processor.py:186} INFO - Started process (PID=885) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:55.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:33:55.974+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:55.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:55.994+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:55.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:33:55.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:56.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:34:28.852+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:34:28.856+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:34:28.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.880+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:34:28.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:34:28.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.061 seconds
[2024-10-14T02:35:02.044+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:02.048+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:02.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.064+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:02.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:35:02.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.050 seconds
[2024-10-14T02:35:35.144+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:35.147+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:35.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.179+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:35.171+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:35.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.065 seconds
[2024-10-14T02:35:56.470+0000] {processor.py:186} INFO - Started process (PID=1136) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:56.473+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.507+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:56.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.066 seconds
[2024-10-14T02:35:56.571+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:56.575+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.595+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:56.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.050 seconds
[2024-10-14T02:36:26.764+0000] {processor.py:186} INFO - Started process (PID=1200) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:36:26.768+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:36:26.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.791+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:36:26.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:36:26.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:37:42.819+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:37:42.827+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.856+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:37:42.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.082 seconds
[2024-10-14T02:38:13.626+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:38:13.628+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.645+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:38:13.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:38:44.238+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:38:44.242+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.259+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:38:44.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.051 seconds
[2024-10-14T02:39:14.992+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:14.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:39:14.999+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:14.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:15.027+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:39:15.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:15.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.071 seconds
[2024-10-14T02:39:45.209+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:39:45.213+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.236+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:39:45.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.076 seconds
[2024-10-14T02:40:15.344+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:40:15.347+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.373+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:40:15.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.053 seconds
[2024-10-14T02:40:46.012+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:40:46.016+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:40:46.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.064 seconds
[2024-10-14T02:41:16.916+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:41:16.919+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.940+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:41:16.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:41:47.233+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:41:47.236+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.256+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:41:47.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.056 seconds
[2024-10-14T02:42:17.745+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:42:17.749+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.771+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:42:17.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:42:48.419+0000] {processor.py:186} INFO - Started process (PID=696) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:42:48.422+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.441+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:42:48.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:43:21.342+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:43:21.346+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.370+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:43:21.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.059 seconds
[2024-10-14T02:43:51.501+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:43:51.512+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.584+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:43:51.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.117 seconds
[2024-10-14T02:44:25.031+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:44:25.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.061+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:44:25.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.069 seconds
[2024-10-14T02:44:57.835+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:44:57.840+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.864+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:44:57.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.061 seconds
[2024-10-14T02:45:30.718+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:45:30.722+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.737+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:45:30.738+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:46:04.030+0000] {processor.py:186} INFO - Started process (PID=1031) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:46:04.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.056+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:46:04.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.063 seconds
[2024-10-14T02:46:37.093+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:46:37.096+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.112+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:46:37.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T02:47:10.243+0000] {processor.py:186} INFO - Started process (PID=1159) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:47:10.246+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.263+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:47:10.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:47:40.660+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:47:40.663+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.678+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:47:40.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
