[2024-10-14T02:26:47.001+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:26:47.006+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:26:47.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.038+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:26:47.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:26:47.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:26:47.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.077 seconds
[2024-10-14T02:27:17.473+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:27:17.476+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:17.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.491+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:17.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:27:17.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:17.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:27:48.009+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:27:48.013+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:48.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.025+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:27:48.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:27:48.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:27:48.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:28:18.711+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:28:18.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:18.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.729+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:18.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:28:18.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:18.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.042 seconds
[2024-10-14T02:28:49.243+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:28:49.247+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:49.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.271+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:28:49.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:28:49.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:28:49.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.063 seconds
[2024-10-14T02:29:20.007+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:29:20.011+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:20.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.029+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:20.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:29:20.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:20.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.062 seconds
[2024-10-14T02:29:50.607+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:29:50.611+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:50.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.622+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:29:50.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:29:50.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:29:50.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.041 seconds
[2024-10-14T02:30:20.967+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:20.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:30:20.971+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:20.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:20.987+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:20.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:30:20.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:21.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:30:51.920+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:30:51.923+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:51.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.944+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:30:51.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:30:51.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:30:51.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.064 seconds
[2024-10-14T02:31:22.992+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:22.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:31:22.997+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:22.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:23.016+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:23.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:31:23.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:23.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:31:53.459+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:31:53.467+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:53.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.494+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:31:53.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:31:53.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:31:53.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.065 seconds
[2024-10-14T02:32:23.697+0000] {processor.py:186} INFO - Started process (PID=755) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:32:23.700+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:23.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:23.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:32:23.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:23.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:32:54.453+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:32:54.459+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:54.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.476+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:32:54.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:32:54.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:32:54.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.051 seconds
[2024-10-14T02:33:25.151+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:33:25.155+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:25.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.170+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:25.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:33:25.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:25.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T02:33:55.970+0000] {processor.py:186} INFO - Started process (PID=885) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:55.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:33:55.974+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:55.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:55.994+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:33:55.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:33:55.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:33:56.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:34:28.852+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:34:28.856+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:34:28.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.880+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:34:28.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:34:28.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:34:28.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.061 seconds
[2024-10-14T02:35:02.044+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:02.048+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:02.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.064+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:02.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'ml'
[2024-10-14T02:35:02.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:02.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.050 seconds
[2024-10-14T02:35:35.144+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:35.147+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:35.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.179+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:35.171+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml.ml import MLSystem  # Importar la clase MLSystem desde ml.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:35.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:35.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.065 seconds
[2024-10-14T02:35:56.470+0000] {processor.py:186} INFO - Started process (PID=1136) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:56.473+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.507+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:56.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.066 seconds
[2024-10-14T02:35:56.571+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:35:56.575+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.595+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:35:56.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:35:56.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:35:56.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.050 seconds
[2024-10-14T02:36:26.764+0000] {processor.py:186} INFO - Started process (PID=1200) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:36:26.768+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:36:26.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.791+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:36:26.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:36:26.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:36:26.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:37:42.819+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:37:42.827+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.856+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:37:42.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:37:42.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.082 seconds
[2024-10-14T02:38:13.626+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:38:13.628+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.645+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:38:13.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:13.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:38:44.238+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:38:44.242+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.259+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:38:44.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:38:44.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.051 seconds
[2024-10-14T02:39:14.992+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:14.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:39:14.999+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:14.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:15.027+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:39:15.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:15.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.071 seconds
[2024-10-14T02:39:45.209+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:39:45.213+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.236+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:39:45.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:39:45.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.076 seconds
[2024-10-14T02:40:15.344+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:40:15.347+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.373+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:40:15.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:15.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.053 seconds
[2024-10-14T02:40:46.012+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:40:46.016+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:40:46.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:40:46.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.064 seconds
[2024-10-14T02:41:16.916+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:41:16.919+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.940+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:41:16.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:16.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:41:47.233+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:41:47.236+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.256+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:41:47.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:41:47.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.056 seconds
[2024-10-14T02:42:17.745+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:42:17.749+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.771+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:42:17.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:17.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.054 seconds
[2024-10-14T02:42:48.419+0000] {processor.py:186} INFO - Started process (PID=696) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:42:48.422+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.441+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:42:48.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:42:48.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:43:21.342+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:43:21.346+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.370+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:43:21.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:21.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.059 seconds
[2024-10-14T02:43:51.501+0000] {processor.py:186} INFO - Started process (PID=781) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:43:51.512+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.584+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:43:51.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:43:51.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.117 seconds
[2024-10-14T02:44:25.031+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:44:25.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.061+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:44:25.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:25.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.069 seconds
[2024-10-14T02:44:57.835+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:44:57.840+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.864+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:44:57.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:44:57.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.061 seconds
[2024-10-14T02:45:30.718+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:45:30.722+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.737+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:45:30.738+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:45:30.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:46:04.030+0000] {processor.py:186} INFO - Started process (PID=1031) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:46:04.035+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.056+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:46:04.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:04.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.063 seconds
[2024-10-14T02:46:37.093+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:46:37.096+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.112+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:46:37.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:46:37.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T02:47:10.243+0000] {processor.py:186} INFO - Started process (PID=1159) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:47:10.246+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.263+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:47:10.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:10.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:47:40.660+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:47:40.663+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.678+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:47:40.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:47:40.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:51:21.651+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:21.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:51:21.655+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:21.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:21.677+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:21.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:51:21.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:21.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.059 seconds
[2024-10-14T02:51:51.905+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:51.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:51:51.908+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:51.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:51.924+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:51.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:51:51.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:51:51.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.048 seconds
[2024-10-14T02:52:22.379+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:22.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:52:22.384+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:22.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:22.408+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:22.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:52:22.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:22.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.061 seconds
[2024-10-14T02:52:52.676+0000] {processor.py:186} INFO - Started process (PID=250) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:52.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:52:52.679+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:52.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:52.695+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:52.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:52:52.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:52:52.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:53:23.088+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:23.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:53:23.091+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:23.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:23.105+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:23.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:53:23.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:23.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.041 seconds
[2024-10-14T02:53:53.287+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:53.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:53:53.291+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:53.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:53.307+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:53.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:53:53.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:53:53.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T02:54:23.569+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:23.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:54:23.573+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:23.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:23.597+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:23.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:54:23.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:23.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:54:54.300+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:54.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:54:54.306+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:54.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:54.329+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:54.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:54:54.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:54:54.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.086 seconds
[2024-10-14T02:55:26.693+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:26.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:55:26.696+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:26.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:26.712+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:26.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:55:26.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:26.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:55:57.561+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:57.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:55:57.564+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:57.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:57.580+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:57.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:55:57.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:55:57.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T02:56:28.580+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:28.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:56:28.583+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:28.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:28.597+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:28.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:56:28.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:28.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.042 seconds
[2024-10-14T02:56:59.651+0000] {processor.py:186} INFO - Started process (PID=762) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:59.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:56:59.655+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:59.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:59.670+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:59.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:56:59.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:56:59.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T02:57:30.568+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:57:30.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:57:30.571+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:57:30.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:57:30.588+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:57:30.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:57:30.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:57:30.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T02:58:01.329+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:01.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:58:01.334+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:01.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:01.352+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:01.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:58:01.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:01.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.055 seconds
[2024-10-14T02:58:32.129+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:32.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:58:32.133+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:32.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:32.158+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:32.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:58:32.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:58:32.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T02:59:02.338+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:02.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:59:02.346+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:02.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:02.367+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:02.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:59:02.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:02.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.166 seconds
[2024-10-14T02:59:32.824+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:32.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T02:59:32.829+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:32.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:32.845+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:32.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T02:59:32.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T02:59:32.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.048 seconds
[2024-10-14T03:00:03.764+0000] {processor.py:186} INFO - Started process (PID=1140) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:03.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:00:03.767+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:03.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:03.781+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:03.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:00:03.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:03.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.041 seconds
[2024-10-14T03:00:34.679+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:34.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:00:34.682+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:34.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:34.697+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:34.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:00:34.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:00:34.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T03:01:05.701+0000] {processor.py:186} INFO - Started process (PID=1268) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:05.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:01:05.705+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:05.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:05.720+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:05.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:01:05.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:05.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.043 seconds
[2024-10-14T03:01:36.161+0000] {processor.py:186} INFO - Started process (PID=1332) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:36.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:01:36.167+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:36.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:36.201+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:36.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:01:36.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:01:36.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.083 seconds
[2024-10-14T03:02:08.471+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:02:08.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:02:08.474+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:02:08.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:02:08.493+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:02:08.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:02:08.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:02:08.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T03:23:32.293+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:23:32.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:23:32.306+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:23:32.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:23:32.326+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:23:32.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:23:32.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:23:32.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.137 seconds
[2024-10-14T03:24:02.527+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:02.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:24:02.531+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:02.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:02.546+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:02.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:24:02.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:02.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.044 seconds
[2024-10-14T03:24:32.793+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:32.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:24:32.798+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:32.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:32.822+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:32.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:24:32.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:24:32.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.064 seconds
[2024-10-14T03:25:03.669+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:03.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:25:03.673+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:03.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:03.691+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:03.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:25:03.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:03.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.047 seconds
[2024-10-14T03:25:34.469+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:34.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:25:34.474+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:34.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:34.489+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:34.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:25:34.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:25:34.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.050 seconds
[2024-10-14T03:26:05.260+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:05.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:26:05.265+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:05.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:05.287+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:05.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:26:05.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:05.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.057 seconds
[2024-10-14T03:26:36.061+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:36.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:26:36.070+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:36.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:36.107+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:36.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:26:36.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:36.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.093 seconds
[2024-10-14T03:26:40.391+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:40.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:26:40.397+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:40.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:40.444+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:40.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 15, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:26:40.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:26:40.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.083 seconds
[2024-10-14T03:27:10.593+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:10.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:10.597+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:10.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:10.611+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:10.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 15, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:10.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:10.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T03:27:23.716+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:23.720+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.744+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:23.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.055 seconds
[2024-10-14T03:27:23.804+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:23.807+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.817+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:23.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.041 seconds
[2024-10-14T03:27:23.881+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:23.884+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.895+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:23.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.039 seconds
[2024-10-14T03:27:23.961+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:23.965+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:23.981+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:23.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:23.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:24.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.046 seconds
[2024-10-14T03:27:24.038+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:24.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:27:24.042+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:24.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:24.056+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:24.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:27:24.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:27:24.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.046 seconds
[2024-10-14T03:28:38.548+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:28:38.550+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:28:38.554+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:28:38.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:28:38.574+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:28:38.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:28:38.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:28:38.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.068 seconds
[2024-10-14T03:29:09.250+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:09.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:29:09.254+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:09.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:09.267+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:09.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:29:09.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:09.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.058 seconds
[2024-10-14T03:29:41.026+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:41.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:29:41.030+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:41.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:41.042+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:41.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:29:41.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:29:41.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.046 seconds
[2024-10-14T03:31:27.636+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:27.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:31:27.640+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:31:27.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:27.655+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:31:27.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:31:27.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:27.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.049 seconds
[2024-10-14T03:31:57.976+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:57.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:31:57.980+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:31:57.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:58.000+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:31:57.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:31:58.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:31:58.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.067 seconds
[2024-10-14T03:32:28.604+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:32:28.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:32:28.608+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:32:28.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:32:28.620+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:32:28.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:32:28.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:32:28.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T03:33:00.039+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:00.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:33:00.043+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:33:00.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:00.054+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:33:00.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:33:00.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:00.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.039 seconds
[2024-10-14T03:33:33.472+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:33.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:33:33.475+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:33:33.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:33.489+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:33:33.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:33:33.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:33:33.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.045 seconds
[2024-10-14T03:34:06.707+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:06.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:34:06.710+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:34:06.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:06.722+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:34:06.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:34:06.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:06.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.038 seconds
[2024-10-14T03:34:39.904+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:39.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:34:39.907+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:34:39.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:39.919+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:34:39.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:34:39.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:34:39.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.040 seconds
[2024-10-14T03:35:13.152+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:13.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:35:13.155+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:35:13.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:13.165+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:35:13.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:35:13.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:13.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.039 seconds
[2024-10-14T03:35:46.144+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:46.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:35:46.147+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:35:46.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:46.159+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:35:46.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:35:46.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:35:46.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.042 seconds
[2024-10-14T03:36:19.338+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:19.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:36:19.342+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:36:19.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:19.404+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:36:19.379+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:36:19.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:19.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.130 seconds
[2024-10-14T03:36:52.253+0000] {processor.py:186} INFO - Started process (PID=683) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:52.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:36:52.265+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:36:52.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:52.281+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:36:52.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:36:52.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:36:52.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.068 seconds
[2024-10-14T03:37:25.565+0000] {processor.py:186} INFO - Started process (PID=746) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:25.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:37:25.572+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:37:25.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:25.593+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:37:25.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:37:25.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:25.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.065 seconds
[2024-10-14T03:37:42.459+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:42.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dmc_pipeline.py for tasks to queue
[2024-10-14T03:37:42.471+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:37:42.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:42.517+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:37:42.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dmc_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dmc_pipeline.py", line 11, in <module>
    from ml import MLSystem
  File "/opt/airflow/dags/ml.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-14T03:37:42.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dmc_pipeline.py
[2024-10-14T03:37:42.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dmc_pipeline.py took 0.087 seconds
