[2024-10-14T02:37:42.836+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/test.py
[2024-10-14T02:37:42.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:37:42.841+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:37:42.876+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:37:42.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:37:42.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2024-10-14T02:38:13.634+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test.py
[2024-10-14T02:38:13.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:38:13.636+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:38:13.647+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:38:13.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:38:13.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:38:44.249+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2024-10-14T02:38:44.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:38:44.252+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:38:44.264+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:38:44.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:38:44.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.041 seconds
[2024-10-14T02:39:15.011+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/test.py
[2024-10-14T02:39:15.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:39:15.018+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:39:15.032+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:39:15.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:39:15.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.054 seconds
[2024-10-14T02:39:45.224+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/test.py
[2024-10-14T02:39:45.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:39:45.228+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:39:45.249+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:39:45.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:39:45.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-10-14T02:40:15.435+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/test.py
[2024-10-14T02:40:15.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:40:15.438+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:40:15.453+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:40:15.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:40:15.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-14T02:40:46.021+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/test.py
[2024-10-14T02:40:46.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:40:46.025+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:40:46.039+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:40:46.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:40:46.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.054 seconds
[2024-10-14T02:41:16.925+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/test.py
[2024-10-14T02:41:16.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:41:16.929+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:41:16.942+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:41:16.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:41:16.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.044 seconds
[2024-10-14T02:41:47.242+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/test.py
[2024-10-14T02:41:47.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:41:47.248+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:41:47.262+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:41:47.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:41:47.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:42:17.754+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/test.py
[2024-10-14T02:42:17.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:42:17.757+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:42:17.773+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:42:17.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:42:17.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:42:48.503+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/test.py
[2024-10-14T02:42:48.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:42:48.506+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:42:48.521+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:42:48.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:42:48.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-14T02:43:21.409+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/test.py
[2024-10-14T02:43:21.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:43:21.413+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:43:21.430+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:43:21.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:43:21.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-14T02:43:51.648+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/test.py
[2024-10-14T02:43:51.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:43:51.652+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:43:51.671+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:43:51.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:43:51.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-14T02:44:25.045+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/test.py
[2024-10-14T02:44:25.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:44:25.049+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:44:25.066+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:44:25.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:44:25.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2024-10-14T02:44:57.843+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/test.py
[2024-10-14T02:44:57.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:44:57.848+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:44:57.864+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:44:57.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:44:57.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.052 seconds
[2024-10-14T02:45:30.727+0000] {processor.py:186} INFO - Started process (PID=968) to work on /opt/airflow/dags/test.py
[2024-10-14T02:45:30.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:45:30.730+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:45:30.740+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:45:30.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:45:30.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:46:04.040+0000] {processor.py:186} INFO - Started process (PID=1032) to work on /opt/airflow/dags/test.py
[2024-10-14T02:46:04.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:46:04.044+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:46:04.062+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:46:04.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:46:04.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2024-10-14T02:46:37.100+0000] {processor.py:186} INFO - Started process (PID=1096) to work on /opt/airflow/dags/test.py
[2024-10-14T02:46:37.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:46:37.103+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:46:37.115+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:46:37.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:46:37.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-14T02:47:10.252+0000] {processor.py:186} INFO - Started process (PID=1160) to work on /opt/airflow/dags/test.py
[2024-10-14T02:47:10.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:47:10.255+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:47:10.267+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:47:10.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:47:10.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-14T02:47:40.668+0000] {processor.py:186} INFO - Started process (PID=1224) to work on /opt/airflow/dags/test.py
[2024-10-14T02:47:40.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:47:40.670+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:47:40.682+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:47:40.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:47:40.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
